### PR TITLE
Expose System.Console.KeyAvailable to the SystemConsole implementation

### PR DESCRIPTION
**Pull request by Hona**

### CODE REVIEW

**Comment by monoclex** [comment]
oh, that'd be a good idea - do you think you could add KeyAvailable all the way up the chain? eg. add it to the IConsole interface and implement the property in every class that implements it?

**Comment by Hona** [comment]
Yeah no worries, will commit it when done

**Comment by Hona** [comment]
Commit also fixed some formatting to comply with your code style

**Comment by monoclex** [comment]
it appears every implementation only checks System.Console.KeyAvailable - if I were to create my own class that implements IConsole and modify the implementation of KeyAvailable and use one of the existing console interfaces to wrap around it, it wouldn't properly fall back to my implementation - it would rely on System.Console. Can you make it so that every KeyAvailable relies on the backing IConsole it gets passed (except for SystemConsole of course)?

**Comment by monoclex** [comment]
that looks good, thank you :+1:

**Pull request merged**
